#!/bin/bash

echo "🔍 HƯỚNG DẪN XEM DATABASE"
echo "=========================="
echo ""
echo "1. Xem qua Prisma Studio (Khuyến nghị):"
echo "   npx prisma studio"
echo ""
echo "2. Xem qua Adminer (Web):"
echo "   http://localhost:8080"
echo "   - System: PostgreSQL"
echo "   - Server: db"
echo "   - User: postgres"
echo "   - Password: postgres"
echo "   - Database: tiny_url"
echo ""
echo "3. Vào database bằng psql:"
echo "   docker compose exec db psql -U postgres -d tiny_url"
echo ""
echo "4. Xem logs database:"
echo "   docker compose logs -f db"
echo ""
echo "5. Xem danh sách tables:"
echo "   docker compose exec db psql -U postgres -d tiny_url -c '\\dt'"
echo ""
echo "6. Xem số lượng links:"
echo "   docker compose exec db psql -U postgres -d tiny_url -c 'SELECT COUNT(*) FROM \"Link\";'"
echo ""
echo "7. Xem số lượng clicks:"
echo "   docker compose exec db psql -U postgres -d tiny_url -c 'SELECT COUNT(*) FROM \"Click\";'"
echo ""

